### ISSUE TITLE
De micșorat paleta de culori folosite pe site

### ISSUE THREAD

**Issue by sandriu** [CatalinFrancu/dexonline#370]
Conform http://www.stylestats.org/?uri=http%3A%2F%2Fdexonline.ro%2F, site-ul folosește acum 27 de culori unice via CSS, majoritatea fiind nuanțe de gri. Paleta de culori ar trebui redusă la 5-6 culori, cu posibile excepții pentru jocuri.

**Comment by CatalinFrancu** [comment]
Mulțumim!
