### ISSUE TITLE
Butonul „Donează” trebuie să rămână vizibil chiar și când bannerul este ascuns

### ISSUE THREAD

**Issue by CatalinFrancu** [CatalinFrancu/dexonline#382]
La cererea publicului. :-)

Pentru afișare, trebuie doar editat `pageLayout.ihtml` linia 74 și eliminată condiția `!$suggestNoBanner`. Problema este la stil, căci la rezoluții mici (1024x768), butonul acoperă caseta cu numărul de rezultate.

Pentru depanare, poți ascunde explicit bannerul din `dex.conf`, secțiunea `[banner]`, opțiunea `type = none`.

![suprapunere](https://cloud.githubusercontent.com/assets/1180392/5124863/d1143294-70c5-11e4-9d2b-74514bf355d2.png)

**Comment by sandriu** [comment]
Am modificat poziția butonului Donează, am testat cu și fără banner:

![fa a_1024x768_no_banner](https://cloud.githubusercontent.com/assets/1265882/6542385/53837cd4-c4ff-11e4-9b22-036b3bfa0315.png)
![fa a_1024x768_with_banner](https://cloud.githubusercontent.com/assets/1265882/6542386/5387661e-c4ff-11e4-9904-b44239d23b1d.png)

**Comment by CatalinFrancu** [comment]
Rezolvat. Vezi și b3a8a98cd3680809bb5e9aea9cf6848b3e479755
