### ISSUE TITLE
Probleme semnalate de GWT pe mobil pe wiki.dexonline.ro

### ISSUE THREAD

**Issue by CatalinFrancu** [CatalinFrancu/dexonline#389]
Cică sunt niște mici probleme pe wiki.dexonline.ro pe mobil. Mie mi se pare că arată bine, dar dacă ne putem conforma mai bine recomandărilor lor, n-ar strica.

![wiki dexonline ro-mobile-issues](https://cloud.githubusercontent.com/assets/1180392/6077819/69b14bfa-adfb-11e4-948e-94b35af8364e.png)

**Comment by raduborza** [comment]
Da, am citit și eu emailul ăla. Eu mă gîndeam că poate ar fi bine să avem
un layout total distinct pe mobil, mult simplificat.

În data de 6 februarie 2015, 12:27, Cătălin Frâncu <notifications@github.com

**Comment by CatalinFrancu** [comment]
Schimbarea se întâmplă [http://searchengineland.com/tomorrow-is-mobilegeddon-are-you-ready-for-the-google-mobile-friendly-update-219291](astăzi). Ar merita să ne asigurăm că suntem considerați mobile-friendly.

**Comment by raduborza** [comment]
Păi cum putem verifica asta?

Din ce am văzut în GWT văd că nu prea-i place că redirectăm la
m.dexonline.ro

Radu

În data de 21 aprilie 2015, 11:36, Cătălin Frâncu <notifications@github.com>
a scris:

**Comment by CatalinFrancu** [comment]
E în regulă, m-am uitat acum în GWT și totul e ok. Sunt vreo 7.000 de pagini cu probleme, dar par vechi și necrawlate de mult.
