### ISSUE TITLE
Mărirea cutiei de căutare pe homepage (desktop)

### ISSUE THREAD

**Issue by sandriu** [CatalinFrancu/dexonline#392]

**Comment by sandriu** [comment]
Atașez screenshot-uri pentru cea mai folosită rezoluție și pentru 1024px.
Notă: pe 1024 homepage-ul arată cam înghesuit, deci box widget-ul din dreapta ar trebui mutat jos de tot sau scos sau micșorat.

![marire-cutie-de-cautare-pe-desktop-pagina-de-rezultate](https://cloud.githubusercontent.com/assets/1265882/6319227/132366b4-babd-11e4-818d-e7dd95ee5062.png)
![marire-cutie-de-cautare-pe-desktop-screenshot-la-1024px](https://cloud.githubusercontent.com/assets/1265882/6319228/1328733e-babd-11e4-8fec-d59daf296f43.png)
![marire-cutie-de-cautare-pe-desktop-screenshot-la-1366px](https://cloud.githubusercontent.com/assets/1265882/6319229/132b80ba-babd-11e4-8822-bd1a4a2da5da.png)

**Comment by raduborza** [comment]
În opinia mea fie schimbăm layout-ul de tot, fie îl simplificăm total la
varianta de mobil.

Dcă mergem pe varianta a doua aș propune să avem doar:
- header cu logare și link către articole și cuvîntul zilei
- input de căutare
- spatiu pentru banner
- spațiu pentru afișarea definițiilor
- dacă este homepage, widgetul din dreapta îl punem orizontal, în partea de
jos a ecranului

Radu

În data de 22 februarie 2015, 18:04, Sonia Andriu <notifications@github.com>
a scris:

**Comment by CatalinFrancu** [comment]
Nu știu dacă parsez bine ce-ai scris tu. :-) Prin _fie îl simplificăm total la varianta de mobil_ vrei să zici să facem interfața de desktop să arate minimalist, ca cea de pe mobil? Asta cred că merită mai mult decât un tichet, merită o discuție în trei (berică?). Cam suferim de feature creeping pe pagina principală, într-adevăr, dar nu e evident la ce să renunțăm.

**Comment by CatalinFrancu** [comment]
De acord cu eliminarea casetei pentru 1024x768. Nu sunt sigur despre stilul cutiei. Acum au rămas doar două elemente care mai au umbră, meniul și caseta din dreapta. Poate ar trebui să renunțăm complet la umbre?

**Comment by raduborza** [comment]
Mda, scuze că eram prolix la ora aia. Ideea e că avem două variante:
- facem un layout comun pentru desktop și mobil și îl facem cît mai simplu,
cu inputuri și butoane mari  - va arăta cam aiurea, dar am văzut că mulți
adoptă trendul ăsta (chiar la google e un tutorial cum să îti proiectezi
layoutul ca să se pupe cu dispozitivele mobile);
- menținem layoutul pentru desktop, dar simplificăm mult layoutul pentru
mobil să fie cu inputuri și butoane mari și mai puține feature-uripe pagină

Tre' să le discutăm la o bere, într-adevăr!

Radu

În data de 25 februarie 2015, 23:39, Cătălin Frâncu <
notifications@github.com> a scris:

**Comment by CatalinFrancu** [comment]
Implementat. Deschid unul separat pentru designul responsive.
