### ISSUE TITLE
Reevaluare fonturi

### ISSUE THREAD

**Issue by CatalinFrancu** [CatalinFrancu/dexonline#396]
Avem o problemă cu fonturile de la Google - din când în când, destul de des, pagina se încarcă în 1-2 secunde. Este clar de la fonturi, pentru că întâi apar cele normale, apoi cele bold etc.

Sonia zice că va căuta niște fonturi care să fie universale pe toate sistemele.

**Comment by raduborza** [comment]
Nu există fonturi universale nici pe același sistem de operare. Niște
familii de fonturi care conțin și ș-urile și ț-urile corecte sînt
suficiente. Sau poate punem o bifă pentru ăia care vor fonturi Google chiar
cu delay-ul respectiv
Pe 7 mar. 2015 10:40, "Cătălin Frâncu" <notifications@github.com> a scris:

**Comment by sandriu** [comment]
Am scos OpenSans, am pus TrebuchetMS și Arial, care ar trebui să fie prezente pe toate cele 3 sisteme de operare (Windows, Mac, Linux), conform acestui tabel http://www.apaddedcell.com/sites/www.apaddedcell.com/files/fonts-article/final/index.html.
Screenshot cu noul font:

![fa a definitie dex online](https://cloud.githubusercontent.com/assets/1265882/6542267/305b124c-c4fc-11e4-9ee2-452fa235436e.png)

**Comment by CatalinFrancu** [comment]
Arată bine. Radu, Sonia e aici lângă mine și zice că n-are nimeni posibilitatea să-ți schimbi fonturile. :-) Eu nu-s împotrivă, dar sună a feature pe care nu l-ar folosi nimeni.
