### ISSUE TITLE
Mobile usability

### ISSUE THREAD

**Issue by CatalinFrancu** [CatalinFrancu/dexonline#397]
Cică Google va începe să penalizeze paginile care nu au mobile usability (bănuiesc că doar în rezultatele afișate pe telefoane mobile). M-am uitat un pic pe raportul din Google Webmaster Tools (ți-am dat și ție drepturi, Sonia). Avem două clase mari de erori, aproape toate pe paginile cu paradigme expandate, de exemplu

http://dexonline.ro/definitie/spanac/paradigma

Erorile sunt (1) conținutul nu încape pe ecran și (2) linkurile sunt prea apropiate. Par erori reale, ar merita reparate.

GWT oferă un întreg ghid cu sugestii pentru corectare.

**Comment by hetmann** [comment]
Cel mai usor e sa verifici paginile web folosind [PageSpeed Insights](https://developers.google.com/speed/pagespeed/insights/)

De exemplu: [http://dexonline.ro/definitie/spanac/paradigma](https://developers.google.com/speed/pagespeed/insights/?url=http%3A%2F%2Fdexonline.ro%2Fdefinitie%2Fspanac%2Fparadigma)

**Comment by liviuroman** [comment]
Pentru a rezolva problema tabelelor mari, care ies din ecran, eu propun să le prin a pune scroll tabelelor. Pentru a înțelege mai bine, am făcut un mic video. https://goo.gl/93nM4t 

Dacă vă place ideea, pot face actualizarea asta :smile:

**Comment by CatalinFrancu** [comment]
Acest tichet este subsumat lui #412.
