### ISSUE TITLE
Suport pentru OAuth 2.0 / OpenID Connect

### ISSUE THREAD

**Issue by CatalinFrancu** [CatalinFrancu/dexonline#401]
Google renunță la suportul pentru OpenID 2.0. Asta va afecta o bună parte din utilizatori, cei care se leagă cu contul Google pe post de OpenID. Google recomandă două soluții, din care una este prea particulară pentru Google (migrarea la Google Sign-In). A doua este migrarea la OAuth 2.0 / OpenID connect.

În fapt, ar trebui să menținem și suportul pentru vechiul protocol, OpenID 2.0, căci par chestii incompatibile și noul protocol are multe bube. Pagina de login poate fi făcută să suporte transparent ambele protocoale și să arate exact ca până acum (o casetă de text pentru tastarea OpenID-ului + butoane pentru Google, Yahoo etc.). Din URL-ul introdus ne putem prinde relativ ușor dacă URL-ul este pentru OpenID 2.0 sau OpenID Connect.

OpenID Connect cere, în principiu, ca noi să ne înregistrăm cu fiecare furnizor de identități și să obținem de la fiecare (1) un ID și (2) un secret. Această cerință este absurdă, căci contravine exact simplificării și unificării pe care o propovăduiește OpenID. Există o portiță: [înregistrarea dinamică](https://www.google.com/search?q=openid+connect+dynamic+registration), prin care putem autentifica un utilizator fără să obținem în prealabil un ID+secret. Nu toată lumea admite această înregistrare dinamică, de exemplu Google nu o admite, insistă să ne înregistrăm la ei.

Deci propunerea ar fi:

* Utilizatorul tastează un URL, caz în care
  * Îl analizăm ca să vedem dacă este OpenID 2.0 sau OpenID connect
  * Pentru OpenID 2.0, facem ce am făcut și până acum
  * Pentru OpenID Connect,
    * Dacă avem deja un ID+secret de la acel provider (de exemplu accounts.google.com), atunci ele vor sta în fișierul de configurare și de acolo ne descurcăm
    * Altfel, dacă providerul admite înregistrare dinamică, putem autentifica utilizatorul
    * Altfel nu putem autentifica utilizatorul. Îi putem oferi un mesaj care înfierează idioțenia acestui sistem. De asemenea, putem salva URL-ul undeva ca să vedem dacă trebuie să ne înregistrăm și la providerul respectiv.
* Utilizatorul apasă pe unul din butoanele existente, caz în care asignăm din cod un URL și revenim la ramura anterioară.

**Comment by CatalinFrancu** [comment]
Observație: una din multele probleme cu noul protocol este că un programator care descarcă codul nostru nu se va putea autentifica cu contul Google în acea instalare locală. El nu va avea acces la secretul nostru de la Google, și chiar dacă ar avea, probabil Google va observa că URL-ul diferă și va refuza să-l autentifice.

**Comment by CatalinFrancu** [comment]
Mă apuc eu de el. @cristiroma, să-mi spui dacă preferi să te las pe tine.

**Comment by cristiroma** [comment]
Dacă te apuci de el fă te rog push pe un branch să pot lua și eu codul, mulțumesc! Momentan sunt cu #299 pe la 80% și se anunță un week-end outdoor.

**Comment by CatalinFrancu** [comment]
Pus în producție. Pare să meargă.
