### ISSUE TITLE
Certificat și https

### ISSUE THREAD

**Issue by CatalinFrancu** [CatalinFrancu/dexonline#407]
Ar fi frumos să avem și noi un certificat și să facem tot traficul pe https.

Dacă ar fi să ne auto-semnăm, trebuie investigat dacă asta va genera warninguri. Nu ar fi bine să devenim unul din acele site-uri care dau warning la prima accesare.

Dacă cumpărăm unul, trebuie să vorbim de bani. :-) Sunt pe la 150 € pe an, parcă, ceea ce nu e ieftin.

**Comment by arthurtiteica** [comment]
Salut,

Într-adevăr, un certificat auto-semnat generează prea multe întrebări în browser.

Pe de altă parte, pentru ce e nevoie aici, StartSSL oferă în mod gratuit certificate cu valabilitate de 1 an. Astfel de certificate la ei se generează pentru un subdomeniu, de ex. www.dexonline.ro dar sunt valabile implicit și pentru domeniul primar dexonline.ro.

Se pot genera genera certificate gratuite pentru oricâte subdomenii este nevoie.

https://www.startssl.com/

**Comment by raduborza** [comment]
Există și certificate gratuite (ți-am dat acum vreo două luni un email
despre asta), dar au și ei niște limitări (limitarea la un singur
subdomeniu).

În data de 27 mai 2015, 10:39, Cătălin Frâncu <notifications@github.com> a
scris:

**Comment by CatalinFrancu** [comment]
Implementat.
