### ISSUE TITLE
Focus or search după încărcarea paginii (mobile)

### ISSUE THREAD

**Issue by cristiroma** [CatalinFrancu/dexonline#413]
Ar fi nice ca după ce se încarcă pagina să poți începe căutarea. Eviți un țap...

**Comment by CatalinFrancu** [comment]
Din câte știu, [nu se poate](http://stackoverflow.com/questions/14362066/jquery-mobile-show-keyboard-on-input-focus). E o decizie de design a telefoanelor mobile, probabil pentru ca paginile să nu abuzeze de asta. Am încercat și cu `autofocus` și cu diverse alte chestii.

**Comment by cristiroma** [comment]
Confirm, închid tichetul deoarece nu cred ca va fi posibilă implementarea pe browser.
